/* AUTOGENERATED FILE - DO NOT EDIT CONTENTS */

export const projectId = "zpbsjgmbvfxhmknryuos"
export const publicAnonKey = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InpwYnNqZ21idmZ4aG1rbnJ5dW9zIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NzIxMDM1NjYsImV4cCI6MjA4NzY3OTU2Nn0.2PkBS38Hxt8Kcf3ftfr7LaGjHemKxstyyTs7Qqo6qNM"

